FROM mcr.microsoft.com/devcontainers/python:dev-3.12-bookworm
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    python3-venv \
    bash-completion 