FROM mcr.microsoft.com/devcontainers/python:dev-3.12-bookworm
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    python3-venv 
    

COPY . /app
WORKDIR /app
RUN make restore && make migrate && make zappa_pack \
    && mv app-dev-*.gz django-demo-dev.tgz \
    && mv handler*.zip handler_stub.zip

FROM scratch
COPY --from=0 /app/django-demo-dev.tgz /app/django-demo-dev.tgz
COPY --from=0 /app/handler_stub.zip /app/handler_stub.zip