FROM mcr.microsoft.com/devcontainers/python:dev-3.12-bookworm
RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get -y install --no-install-recommends \
    python3-venv 
    

COPY . /app
WORKDIR /app
RUN make restore && make migrate && make zappa_pack && mv app-dev-*.zip django-demo-dev.zip

FROM scratch
COPY --from=0 /app/django-demo-dev.zip /app/django-demo-dev.zip